
#ifndef  AM437X_PRCM_H__
#define  AM437X_PRCM_H__
//#include  "AM437X_PRCM.h"


#include  "AM437X_DataType.h"
#include  "AM437X_Mapping.h"

//#define 	PRCM_CM_PER_GPIO1_CLKCTRL  (*(volatile unsigned long *)(CM_PER + 0x478) )
//²Î¿¼ÊÖ²á553-555
//#define 	PRCM_CM_WKUP_CLKSTCTRL    		   (*(volatile unsigned long *)(CM_WKUP + 0x300) )
//#define 	PRCM_CM_WKUP_UART0_CLKCTRL		   (*(volatile unsigned long *)(CM_WKUP + 0x348) )



//P300
#define				PRCM_PM_CEFUSE_PWRSTCTRL                  (*(volatile unsigned int  *)(PRM_CEFUSE_BASE + 0x00))
#define				PRCM_PM_CEFUSE_PWRSTST                    (*(volatile unsigned int  *)(PRM_CEFUSE_BASE + 0x04))
#define				PRCM_RM_CEFUSE_CONTEXT                    (*(volatile unsigned int  *)(PRM_CEFUSE_BASE + 0x24))
//P303 				
#define				PRCM_PRM_RSTCTRL                          (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x00))
#define				PRCM_PRM_RSTST                            (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x04))
#define				PRCM_PRM_RSTTIME                   		    (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x08))
#define				PRCM_PRM_SRAM_COUNT                  	    (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x0C))
#define				PRCM_PRM_LDO_SRAM_CORE_SETUP              (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x10))
#define				PRCM_PRM_LDO_SRAM_CORE_CTRL               (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x14))
#define				PRCM_PRM_LDO_SRAM_MPU_SETUP               (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x18))
#define				PRCM_PRM_LDO_SRAM_MPU_CTRL                (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x1C))
#define				PRCM_PRM_IO_COUNT                    	    (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x20))
#define				PRCM_PRM_IO_PMCTRL                  	    (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x24))
#define				PRCM_PRM_VC_VAL_BYPASS                    (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x28))
#define				PRCM_PRM_EMIF_CTRL                 	      (*(volatile unsigned int  *)(PRM_DEVICE_BASE + 0x30))
//P319 				
#define				PRCM_PRM_PM_GFX_PWRSTCTRL                 (*(volatile unsigned int  *)(PRM_GFX_BASE + 0x00))
#define				PRCM_PRM_PM_GFX_PWRSTST                   (*(volatile unsigned int  *)(PRM_GFX_BASE + 0x04))
#define				PRCM_PRM_RM_GFX_RSTCTRL                   (*(volatile unsigned int  *)(PRM_GFX_BASE + 0x10))
#define				PRCM_PRM_RM_GFX_RSTST                  	  (*(volatile unsigned int  *)(PRM_GFX_BASE + 0x14))
#define				PRCM_PRM_RM_GFX_CONTEXT                   (*(volatile unsigned int  *)(PRM_GFX_BASE + 0x24))
//P324 				
#define				PRCM_PM_MPU_PWRSTCTRL                     (*(volatile unsigned int  *)(PRM_MPU_BASE + 0x00))
#define				PRCM_PM_MPU_PWRSTST                       (*(volatile unsigned int  *)(PRM_MPU_BASE + 0x04))
#define				PRCM_RM_MPU_RSTST                         (*(volatile unsigned int  *)(PRM_MPU_BASE + 0x14))
#define				PRCM_RM_MPU_CONTEXT                  	    (*(volatile unsigned int  *)(PRM_MPU_BASE + 0x24))
//P324 				
#define				PRCM_PM_MPU_PWRSTCTRL                     (*(volatile unsigned int  *)(PRM_MPU_BASE + 0x00))
#define				PRCM_PM_MPU_PWRSTST                       (*(volatile unsigned int  *)(PRM_MPU_BASE + 0x04))
#define				PRCM_RM_MPU_RSTST                         (*(volatile unsigned int  *)(PRM_MPU_BASE + 0x14))
#define				PRCM_RM_MPU_CONTEXT                  	    (*(volatile unsigned int  *)(PRM_MPU_BASE + 0x24))
//P331 				
#define				PRCM_PM_PER_PWRSTCTRL                     (*(volatile unsigned int  *)(PRM_PER_BASE + 0x000)) 
#define				PRCM_PM_PER_PWRSTST                       (*(volatile unsigned int  *)(PRM_PER_BASE + 0x004)) 
#define				PRCM_RM_PER_RSTCTRL                       (*(volatile unsigned int  *)(PRM_PER_BASE + 0x010)) 
#define				PRCM_RM_PER_RSTST                         (*(volatile unsigned int  *)(PRM_PER_BASE + 0x014)) 
#define				PRCM_RM_PER_L3_CONTEXT                    (*(volatile unsigned int  *)(PRM_PER_BASE + 0x024)) 
#define				PRCM_RM_PER_L3_INSTR_CONTEXT              (*(volatile unsigned int  *)(PRM_PER_BASE + 0x044))                                                        
#define				PRCM_RM_PER_OCMCRAM_CONTEXT               (*(volatile unsigned int  *)(PRM_PER_BASE + 0x054))                                                         
#define				PRCM_RM_PER_VPFE0_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x06C)) 
#define				PRCM_RM_PER_VPFE1_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x074))                          
#define				PRCM_RM_PER_TPCC_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x07C)) 
#define				PRCM_RM_PER_TPTC0_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x084)) 
#define				PRCM_RM_PER_TPTC1_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x08C)) 
#define				PRCM_RM_PER_TPTC2_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x094)) 
#define				PRCM_RM_PER_DLL_AGING_CONTEXT             (*(volatile unsigned int  *)(PRM_PER_BASE + 0x09C))                                                        
#define				PRCM_RM_PER_L4HS_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x0A4)) 
#define				PRCM_RM_PER_GPMC_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x224))
#define				PRCM_RM_PER_ADC1_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x234))
#define				PRCM_RM_PER_MCASP0_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x23C))
#define				PRCM_RM_PER_MCASP1_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x244))
#define				PRCM_RM_PER_MMC2_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x24C))
#define				PRCM_RM_PER_QSPI_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x25C))
#define				PRCM_RM_PER_USB_OTG_SS0_CONTEXT           (*(volatile unsigned int  *)(PRM_PER_BASE + 0x264))                                                          
#define				PRCM_RM_PER_USB_OTG_SS1_CO                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x26C))                                                                  
#define				PRCM_RM_PER_PRU_ICSS_CONTEXT              (*(volatile unsigned int  *)(PRM_PER_BASE + 0x324))                                                           
#define				PRCM_RM_PER_L4LS_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x424))
#define				PRCM_RM_PER_DCAN0_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x42C))
#define				PRCM_RM_PER_DCAN1_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x434))
#define				PRCM_RM_PER_PWMSS0_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x43C))
#define				PRCM_RM_PER_PWMSS1_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x444))
#define				PRCM_RM_PER_PWMSS2_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x44C))
#define				PRCM_RM_PER_PWMSS3_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x454))
#define				PRCM_RM_PER_PWMSS4_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x45C))
#define				PRCM_RM_PER_PWMSS5_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x464))
#define				PRCM_RM_PER_ELM_CONTEXT                   (*(volatile unsigned int  *)(PRM_PER_BASE + 0x46C))
#define				PRCM_RM_PER_GPIO1_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x47C))
#define				PRCM_RM_PER_GPIO2_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x484))
#define				PRCM_RM_PER_GPIO3_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x48C))
#define				PRCM_RM_PER_GPIO4_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x494))
#define				PRCM_RM_PER_GPIO5_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x49C))
#define				PRCM_RM_PER_HDQ1W_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x4A4))
#define				PRCM_RM_PER_I2C1_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x4AC))
#define				PRCM_RM_PER_I2C2_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x4B4))
#define				PRCM_RM_PER_MAILBOX0_CONTEXT              (*(volatile unsigned int  *)(PRM_PER_BASE + 0x4BC))                             
#define				PRCM_RM_PER_MMC0_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x4C4))       
#define				PRCM_RM_PER_MMC1_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x4CC))
#define				PRCM_RM_PER_SPI0_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x504))
#define				PRCM_RM_PER_SPI1_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x50C))
#define				PRCM_RM_PER_SPI2_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x514))
#define				PRCM_RM_PER_SPI3_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x51C))
#define				PRCM_RM_PER_SPI4_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x524))
#define				PRCM_RM_PER_SPINLOCK_CONTEXT              (*(volatile unsigned int  *)(PRM_PER_BASE + 0x52C))                                                        
#define				PRCM_RM_PER_TIMER2_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x534))
#define				PRCM_RM_PER_TIMER3_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x53C))
#define				PRCM_RM_PER_TIMER4_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x544))
#define				PRCM_RM_PER_TIMER5_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x54C))
#define				PRCM_RM_PER_TIMER6_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x554))
#define				PRCM_RM_PER_TIMER7_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x55C))
#define				PRCM_RM_PER_TIMER8_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x564))
#define				PRCM_RM_PER_TIMER9_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x56C))
#define				PRCM_RM_PER_TIMER10_CONTEXT               (*(volatile unsigned int  *)(PRM_PER_BASE + 0x574))
#define				PRCM_RM_PER_TIMER11_CONTEXT               (*(volatile unsigned int  *)(PRM_PER_BASE + 0x57C))
#define				PRCM_RM_PER_UART1_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x584))
#define				PRCM_RM_PER_UART2_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x58C))
#define				PRCM_RM_PER_UART3_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x594))
#define				PRCM_RM_PER_UART4_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x59C))
#define				PRCM_RM_PER_UART5_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x5A4))
#define				PRCM_RM_PER_USBPHYOCP2SCP0_CONTEXT        (*(volatile unsigned int  *)(PRM_PER_BASE + 0x5BC))                                                       
#define				PRCM_RM_PER_USBPHYOCP2SCP1_CONTEXT        (*(volatile unsigned int  *)(PRM_PER_BASE + 0x5C4))                                           
#define				PRCM_RM_PER_EMIF_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x724))
#define				PRCM_RM_PER_DLL_CONTEXT                   (*(volatile unsigned int  *)(PRM_PER_BASE + 0x72C))
#define				PRCM_RM_PER_DSS_CONTEXT                   (*(volatile unsigned int  *)(PRM_PER_BASE + 0xA24))
#define				PRCM_RM_PER_CPGMAC0_CONTEXT               (*(volatile unsigned int  *)(PRM_PER_BASE + 0xB24))                                                 
#define				PRCM_RM_PER_OCPWP_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0xC24))
#define				PRCM_RM_PER_MMC0_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x4C4))
#define				PRCM_RM_PER_MMC1_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x4CC))
#define				PRCM_RM_PER_SPI0_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x504))
#define				PRCM_RM_PER_SPI1_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x50C))
#define				PRCM_RM_PER_SPI2_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x514))
#define				PRCM_RM_PER_SPI3_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x51C))
#define				PRCM_RM_PER_SPI4_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x524))
#define				PRCM_RM_PER_SPINLOCK_CONTEXT              (*(volatile unsigned int  *)(PRM_PER_BASE + 0x52C))                                                             
#define				PRCM_RM_PER_TIMER2_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x534))
#define				PRCM_RM_PER_TIMER3_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x53C))
#define				PRCM_RM_PER_TIMER4_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x544))
#define				PRCM_RM_PER_TIMER5_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x54C))
#define				PRCM_RM_PER_TIMER6_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x554))
#define				PRCM_RM_PER_TIMER7_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x55C))
#define				PRCM_RM_PER_TIMER8_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x564))
#define				PRCM_RM_PER_TIMER9_CONTEXT                (*(volatile unsigned int  *)(PRM_PER_BASE + 0x56C))
#define				PRCM_RM_PER_TIMER10_CONTEXT               (*(volatile unsigned int  *)(PRM_PER_BASE + 0x574))
#define				PRCM_RM_PER_TIMER11_CONTEXT               (*(volatile unsigned int  *)(PRM_PER_BASE + 0x57C))
#define				PRCM_RM_PER_UART1_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x584))
#define				PRCM_RM_PER_UART2_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x58C))
#define				PRCM_RM_PER_UART3_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x594))
#define				PRCM_RM_PER_UART4_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x59C))
#define				PRCM_RM_PER_UART5_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0x5A4))
#define				PRCM_RM_PER_USBPHYOCP2SCP0_CONTEXT        (*(volatile unsigned int  *)(PRM_PER_BASE + 0x5BC))                                                             
#define				PRCM_RM_PER_USBPHYOCP2SCP1_CONTEXT        (*(volatile unsigned int  *)(PRM_PER_BASE + 0x5C4))                                                            
#define				PRCM_RM_PER_EMIF_CONTEXT                  (*(volatile unsigned int  *)(PRM_PER_BASE + 0x724))
#define				PRCM_RM_PER_DLL_CONTEXT                   (*(volatile unsigned int  *)(PRM_PER_BASE + 0x72C))
#define				PRCM_RM_PER_DSS_CONTEXT                   (*(volatile unsigned int  *)(PRM_PER_BASE + 0xA24))
#define				PRCM_RM_PER_CPGMAC0_CONTEXT               (*(volatile unsigned int  *)(PRM_PER_BASE + 0xB24))                                                             
#define				PRCM_RM_PER_OCPWP_CONTEXT                 (*(volatile unsigned int  *)(PRM_PER_BASE + 0xC24))
       				
       				
       				
//P432 				
#define				PRCM_CM_CEFUSE_CLKSTCTRLL                 (*(volatile unsigned int  *)(CM_CEFUSE_BASE + 0x00))
#define				PRCM_CM_CEFUSE_CLKCTRL                    (*(volatile unsigned int  *)(CM_CEFUSE_BASE + 0x20))
//P435 				 
#define				PRCM_CM_CLKOUT1_CTRL           		        (*(volatile unsigned int  *)(CM_DEVICE_BASE + 0x00))
#define				PRCM_CM_DLL_CTRL              		        (*(volatile unsigned int  *)(CM_DEVICE_BASE + 0x04))
#define				PRCM_CM_CLKOUT2_CTRL                      (*(volatile unsigned int  *)(CM_DEVICE_BASE + 0x08))
//P440 				
#define				PRCM_CM_DPLL_DPLL_CLKSEL_TIMER1_CLK       (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x00))
#define				PRCM_CM_DPLL_CLKSEL_TIMER2_CLK            (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x04))
#define				PRCM_CM_DPLL_CLKSEL_TIMER3_CLK            (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x08))
#define				PRCM_CM_DPLL_CLKSEL_TIMER4_CLK            (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x0C))
#define				PRCM_CM_DPLL_CLKSEL_TIMER5_CLK            (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x10))
#define				PRCM_CM_DPLL_CLKSEL_TIMER6_CLK            (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x14))
#define				PRCM_CM_DPLL_CLKSEL_TIMER7_CLK            (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x18))
#define				PRCM_CM_DPLL_CLKSEL_TIMER8_CLK            (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x1C))
#define				PRCM_CM_DPLL_CLKSEL_TIMER9_CLK            (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x20))
#define				PRCM_CM_DPLL_CLKSEL_TIMER10_CLK           (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x24))
#define				PRCM_CM_DPLL_CLKSEL_TIMER11_CLK           (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x28))
#define				PRCM_CM_DPLL_CLKSEL_WDT1_CLK              (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x2C))
#define				PRCM_CM_DPLL_CLKSEL_SYNCTIMER_CLK         (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x30))
#define				PRCM_CM_DPLL_CLKSEL_MAC_CLK               (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x34))
#define				PRCM_CM_DPLL_CLKSEL_CPTS_RFT_CLK          (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x38))
#define				PRCM_CM_DPLL_CLKSEL_GFX_FCLK              (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x3C))
#define				PRCM_CM_DPLL_CLKSEL_GPIO0_DBCLK           (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x40))
#define				PRCM_CM_CLKSEL_PRU_ICSS_OCP_CLK           (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x48))
#define				PRCM_CM_CLKSEL_ADC1_CLK                   (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x4C))
#define				PRCM_CM_DPLL_CLKSEL_DLL_AGING_CLK         (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x50))
#define				PRCM_CM_DPLL_CLKSEL_USBPHY32KHZ_GCLK      (*(volatile unsigned int  *)(CM_DPLL_BASE + 0x60))             
//P462 				
#define				PRCM_CM_GFX_L3_CLKSTCTRL                  (*(volatile unsigned int  *)(CM_GFX_BASE + 0x00))
#define				PRCM_CM_GFX_CLKCTRL                       (*(volatile unsigned int  *)(CM_GFX_BASE + 0x20))
//P465 				
#define				PRCM_CM_MPU_CLKSTCTRL                     (*(volatile unsigned int  *)(CM_MPU_BASE + 0x00))
#define				PRCM_CM_MPU_CLKCTRL                       (*(volatile unsigned int  *)(CM_MPU_BASE + 0x20))
//P467 				
#define				PRCM_CM_PER_L3_CLKSTCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x00))
#define				PRCM_CM_PER_L3_CLKCTRL                	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x20))
#define				PRCM_CM_PER_L3_INSTR_CLKCTRL          	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x40))
#define				PRCM_CM_PER_OCMCRAM_CLKCTRL           	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x50))
#define				PRCM_CM_PER_VPFE0_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x68))
#define				PRCM_CM_PER_VPFE1_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x70))
#define				PRCM_CM_PER_TPCC_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x78))
#define				PRCM_CM_PER_TPTC0_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x80))
#define				PRCM_CM_PER_TPTC1_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x88))
#define				PRCM_CM_PER_TPTC2_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x90))
#define				PRCM_CM_PER_DLL_AGING_CLKCTRL         	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x98))
#define				PRCM_CM_PER_L4HS_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0xA0))
#define				PRCM_CM_PER_L3S_CLKSTCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x200))
#define				PRCM_CM_PER_GPMC_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x220))
#define				PRCM_CM_PER_ADC1_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x230))
#define				PRCM_CM_PER_MCASP0_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x238))
#define				PRCM_CM_PER_MCASP1_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x240))
#define				PRCM_CM_PER_MMC2_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x248))
#define				PRCM_CM_PER_QSPI_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x258))
#define				PRCM_CM_PER_USB_OTG_SS0_CLKCTRL       	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x260))
#define				PRCM_CM_PER_USB_OTG_SS1_CLKCTRL       	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x268))
#define				PRCM_CM_PER_PRU_ICSS_CLKSTCTRL        	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x300))
#define				PRCM_CM_PER_PRU_ICSS_CLKCTRL          	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x320))
#define				PRCM_CM_PER_L4LS_CLKSTCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x400))
#define				PRCM_CM_PER_L4LS_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x420))
#define				PRCM_CM_PER_DCAN0_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x428))
#define				PRCM_CM_PER_DCAN1_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x430))
#define				PRCM_CM_PER_PWMSS0_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x438))
#define				PRCM_CM_PER_PWMSS1_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x440))
#define				PRCM_CM_PER_PWMSS2_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x448))
#define				PRCM_CM_PER_PWMSS3_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x450))
#define				PRCM_CM_PER_PWMSS4_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x458))
#define				PRCM_CM_PER_PWMSS5_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x460))
#define				PRCM_CM_PER_ELM_CLKCTRL               	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x468))
#define				PRCM_CM_PER_GPIO1_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x478))
#define				PRCM_CM_PER_GPIO2_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x480))
#define				PRCM_CM_PER_GPIO3_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x488))
#define				PRCM_CM_PER_GPIO4_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x490))
#define				PRCM_CM_PER_GPIO5_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x498))
#define				PRCM_CM_PER_HDQ1W_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x4A0))
#define				PRCM_CM_PER_I2C1_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x4A8))
#define				PRCM_CM_PER_I2C2_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x4B0))
#define				PRCM_CM_PER_MAILBOX0_CLKCTRL          	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x4B8))
#define				PRCM_CM_PER_MMC0_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x4C0))
#define				PRCM_CM_PER_MMC1_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x4C8))
#define				PRCM_CM_PER_SPI0_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x500))
#define				PRCM_CM_PER_SPI1_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x508))
#define				PRCM_CM_PER_SPI2_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x510))
#define				PRCM_CM_PER_SPI3_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x518))
#define				PRCM_CM_PER_SPI4_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x520))
#define				PRCM_CM_PER_SPINLOCK_CLKCTRL          	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x528))
#define				PRCM_CM_PER_TIMER2_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x530))
#define				PRCM_CM_PER_TIMER3_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x538))
#define				PRCM_CM_PER_TIMER4_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x540))
#define				PRCM_CM_PER_TIMER5_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x548))
#define				PRCM_CM_PER_TIMER6_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x550))
#define				PRCM_CM_PER_TIMER7_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x558))
#define				PRCM_CM_PER_TIMER8_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x560))
#define				PRCM_CM_PER_TIMER9_CLKCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x568))
#define				PRCM_CM_PER_TIMER10_CLKCTRL           	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x570))
#define				PRCM_CM_PER_TIMER11_CLKCTRL           	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x578))
#define				PRCM_CM_PER_UART1_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x580))
#define				PRCM_CM_PER_UART2_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x588))
#define				PRCM_CM_PER_UART3_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x590))
#define				PRCM_CM_PER_UART4_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x598))
#define				PRCM_CM_PER_UART5_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x5A0))
#define				PRCM_CM_PER_USBPHYOCP2SCP0_CLKCTRL    	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x5B8))
#define				PRCM_CM_PER_USBPHYOCP2SCP1_CLKCTRL    	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x5C0))
#define				PRCM_CM_PER_EMIF_CLKSTCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x700))
#define				PRCM_CM_PER_EMIF_CLKCTRL              	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x720))
#define				PRCM_CM_PER_DLL_CLKCTRL               	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x728))
#define				PRCM_CM_PER_LCDC_CLKSTCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0x800))
#define				PRCM_CM_PER_DSS_CLKSTCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0xA00))
#define				PRCM_CM_PER_DSS_CLKCTRL               	  (*(volatile unsigned int  *)(CM_PER_BASE + 0xA20))
#define				PRCM_CM_PER_CPSW_CLKSTCTRL            	  (*(volatile unsigned int  *)(CM_PER_BASE + 0xB00))
#define				PRCM_CM_PER_CPGMAC0_CLKCTRL           	  (*(volatile unsigned int  *)(CM_PER_BASE + 0xB20))
#define				PRCM_CM_PER_OCPWP_L3_CLKSTCTRL        	  (*(volatile unsigned int  *)(CM_PER_BASE + 0xC00))
#define				PRCM_CM_PER_OCPWP_CLKCTRL             	  (*(volatile unsigned int  *)(CM_PER_BASE + 0xC20))
//P551 				
#define				PRCM_CM_RTC_CLKSTCTRL                     (*(volatile unsigned int  *)(CM_RTC_BASE + 0x00))
#define				PRCM_CM_RTC_CLKCTRL                       (*(volatile unsigned int  *)(CM_RTC_BASE + 0x20))
//P553 				
#define				PRCM_CM_L3_AON_CLKSTCTRL                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x00))   
#define				PRCM_CM_WKUP_DBGSS_CLKCTRL                (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x20))   
#define				PRCM_CM_L3S_ADC0_CLKSTCTRL                (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x100))   
#define				PRCM_CM_WKUP_ADC0_CLKCTRL                 (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x120))   
#define				PRCM_CM_L4_WKUP_AON_CLKSTCTRL             (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x200))   
#define				PRCM_CM_WKUP_L4WKUP_CLKCTRL               (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x220))   
#define				PRCM_CM_WKUP_PROC_CLKCTRL                 (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x228))   
#define				PRCM_CM_WKUP_SYNCTIMER_CLKCTRL            (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x230))   
#define				PRCM_CM_WKUP_CLKDIV32K_CLKCTRL            (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x238))   
#define				PRCM_CM_WKUP_USBPHY0_CLKCTRL              (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x240))   
#define				PRCM_CM_WKUP_USBPHY1_CLKCTRL              (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x248))   
#define				PRCM_CM_WKUP_CLKSTCTRL                    (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x300))   
#define				PRCM_CM_WKUP_TIMER0_CLKCTRL               (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x320))   
#define				PRCM_CM_WKUP_TIMER1_CLKCTRL               (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x328))   
#define				PRCM_CM_WKUP_WDT1_CLKCTRL                 (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x338))   
#define				PRCM_CM_WKUP_I2C0_CLKCTRL                 (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x340))   
#define				PRCM_CM_WKUP_UART0_CLKCTRL                (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x348))   
#define				PRCM_CM_WKUP_CTRL_CLKCTRL                 (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x360))   
#define				PRCM_CM_WKUP_GPIO0_CLKCTRL                (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x368))   
#define				PRCM_CM_CLKMODE_DPLL_CORE                 (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x520))   
#define				PRCM_CM_IDLEST_DPLL_CORE                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x524))   
#define				PRCM_CM_CLKSEL_DPLL_CORE                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x52C))   
#define				PRCM_CM_DIV_M4_DPLL_CORE                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x538))   
#define				PRCM_CM_DIV_M5_DPLL_CORE                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x53C))   
#define				PRCM_CM_DIV_M6_DPLL_CORE                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x540))   
#define				PRCM_CM_SSC_DELTAMSTEP_DPLL_CORE          (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x548))   
#define				PRCM_CM_SSC_MODFREQDIV_DPLL_CORE          (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x54C))   
#define				PRCM_CM_CLKMODE_DPLL_MPU                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x560))   
#define				PRCM_CM_IDLEST_DPLL_MPU                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x564))   
#define				PRCM_CM_CLKSEL_DPLL_MPU                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x56C))   
#define				PRCM_CM_DIV_M2_DPLL_MPU                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x570))   
#define				PRCM_CM_SSC_DELTAMSTEP_DPLL_MPU           (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x588))   
#define				PRCM_CM_SSC_MODFREQDIV_DPLL_MPU           (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x58C))   
#define				PRCM_CM_CLKMODE_DPLL_DDR                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5A0))   
#define				PRCM_CM_IDLEST_DPLL_DDR                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5A4))   
#define				PRCM_CM_CLKSEL_DPLL_DDR                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5AC))   
#define				PRCM_CM_DIV_M2_DPLL_DDR                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5B0))   
#define				PRCM_CM_DIV_M4_DPLL_DDR                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5B8))   
#define				PRCM_CM_SSC_DELTAMSTEP_DPLL_DDR           (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5C8))   
#define				PRCM_CM_SSC_MODFREQDIV_DPLL_DDR           (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5CC))   
#define				PRCM_CM_CLKMODE_DPLL_PER                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5E0))   
#define				PRCM_CM_IDLEST_DPLL_PER                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5E4))   
#define				PRCM_CM_CLKSEL_DPLL_PER                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5EC))   
#define				PRCM_CM_DIV_M2_DPLL_PER                   (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x5F0))   
#define				PRCM_CM_CLKSEL2_DPLL_PER                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x604))   
#define				PRCM_CM_SSC_DELTAMSTEP_DPLL_PER           (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x608))   
#define				PRCM_CM_SSC_MODFREQDIV_DPLL_PER           (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x60C))   
#define				PRCM_CM_CLKDCOLDO_DPLL_PER                (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x614))   
#define				PRCM_CM_CLKMODE_DPLL_DISP                 (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x620))   
#define				PRCM_CM_IDLEST_DPLL_DISP                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x624))   
#define				PRCM_CM_CLKSEL_DPLL_DISP                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x62C))   
#define				PRCM_CM_DIV_M2_DPLL_DISP                  (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x630))   
#define				PRCM_CM_SSC_DELTAMSTEP_DPLL_DISP          (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x648))   
#define				PRCM_CM_SSC_MODFREQDIV_DPLL_DISP          (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x64C))   
#define				PRCM_CM_CLKMODE_DPLL_EXTDEV               (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x660))   
#define				PRCM_CM_IDLEST_DPLL_EXTDEV                (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x664))   
#define				PRCM_CM_CLKSEL_DPLL_EXTDEV                (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x66C))   
#define				PRCM_CM_DIV_M2_DPLL_EXTDEV                (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x670))   
#define				PRCM_CM_CLKSEL2_DPLL_EXTDEV               (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x684))   
#define				PRCM_CM_SSC_DELTAMSTEP_DPLL_EXTDEV        (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x688))   
#define				PRCM_CM_SSC_MODFREQDIV_DPLL_EXTDEV        (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x68C))   
#define				PRCM_CM_SHADOW_FREQ_CONFIG1               (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x7A0))   
#define				PRCM_CM_SHADOW_FREQ_CONFIG2               (*(volatile unsigned int  *)(CM_WKUP_BASE + 0x7A4))   




#endif
